
// Generated by Cadence Encounter(R) RTL Compiler RC14.25 - v14.20-s046_1

// Verification Directory fv/project_top 

module bitwiseand(A, B, out);
  input [3:0] A, B;
  output [3:0] out;
  wire [3:0] A, B;
  wire [3:0] out;
  AND2XL g29(.A (B[3]), .B (A[3]), .Y (out[3]));
  AND2XL g30(.A (B[2]), .B (A[2]), .Y (out[2]));
  AND2XL g31(.A (B[0]), .B (A[0]), .Y (out[0]));
  AND2XL g32(.A (B[1]), .B (A[1]), .Y (out[1]));
endmodule

module counter(clk, en, out);
  input clk, en;
  output [3:0] out;
  wire clk, en;
  wire [3:0] out;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_15, n_17;
  NAND2XL g91(.A (n_11), .B (n_10), .Y (out[0]));
  OAI2BB1X1 g92(.A0N (count[2]), .A1N (count[3]), .B0 (n_11), .Y
       (out[1]));
  CLKINVX1 g94(.A (n_11), .Y (out[3]));
  NOR2XL g95(.A (count[1]), .B (count[0]), .Y (n_11));
  XNOR2XL g2(.A (count[3]), .B (count[2]), .Y (n_10));
  DFFQX4 \count_reg[3] (.CK (clk), .D (n_9), .Q (count[3]));
  NOR2BXL g151(.AN (en), .B (n_8), .Y (n_9));
  DFFQX1 \count_reg[2] (.CK (clk), .D (n_7), .Q (count[2]));
  AOI21X1 g153(.A0 (count[3]), .A1 (n_3), .B0 (n_6), .Y (n_8));
  AND2XL g154(.A (n_4), .B (en), .Y (n_7));
  NOR2XL g155(.A (count[3]), .B (n_3), .Y (n_6));
  NOR2BXL g157(.AN (en), .B (n_2), .Y (n_5));
  CLKXOR2X1 g158(.A (count[2]), .B (n_0), .Y (n_4));
  NAND2XL g160(.A (count[2]), .B (n_0), .Y (n_3));
  XNOR2XL g161(.A (count[0]), .B (count[1]), .Y (n_2));
  AND2XL g162(.A (n_15), .B (en), .Y (n_1));
  NOR2XL g163(.A (n_17), .B (n_15), .Y (n_0));
  DFFX2 \count_reg[1] (.CK (clk), .D (n_5), .Q (count[1]), .QN (n_17));
  DFFX1 \count_reg[0] (.CK (clk), .D (n_1), .Q (count[0]), .QN (n_15));
endmodule

module pencoder(A, Out);
  input [3:0] A;
  output [1:0] Out;
  wire [3:0] A;
  wire [1:0] Out;
  wire n_0, n_1;
  OAI21X1 g17(.A0 (A[2]), .A1 (n_0), .B0 (n_1), .Y (Out[0]));
  NAND2BX1 g18(.AN (A[2]), .B (n_1), .Y (Out[1]));
  CLKINVX1 g19(.A (A[3]), .Y (n_1));
  CLKINVX1 g20(.A (A[1]), .Y (n_0));
endmodule

module pencoder_5(A, Out);
  input [3:0] A;
  output [1:0] Out;
  wire [3:0] A;
  wire [1:0] Out;
  wire n_0, n_1;
  OAI21X1 g17(.A0 (A[2]), .A1 (n_0), .B0 (n_1), .Y (Out[0]));
  NAND2BX1 g18(.AN (A[2]), .B (n_1), .Y (Out[1]));
  CLKINVX1 g19(.A (A[3]), .Y (n_1));
  CLKINVX1 g20(.A (A[1]), .Y (n_0));
endmodule

module unequal(A, B, out);
  input [3:0] A, B;
  output [3:0] out;
  wire [3:0] A, B;
  wire [3:0] out;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  NAND4XL g115(.A (n_0), .B (n_7), .C (n_1), .D (n_8), .Y (out[3]));
  AOI22X1 g116(.A0 (A[1]), .A1 (n_3), .B0 (A[2]), .B1 (n_5), .Y (n_8));
  AOI22X1 g117(.A0 (B[1]), .A1 (n_4), .B0 (B[2]), .B1 (n_6), .Y (n_7));
  CLKINVX1 g121(.A (A[2]), .Y (n_6));
  INVXL g122(.A (B[2]), .Y (n_5));
  CLKINVX1 g123(.A (A[1]), .Y (n_4));
  INVXL g125(.A (B[1]), .Y (n_3));
  XNOR2XL g2(.A (A[3]), .B (B[3]), .Y (n_1));
  XNOR2XL g126(.A (A[0]), .B (B[0]), .Y (n_0));
endmodule

module project_top(clk, A, B, C, out);
  input clk;
  input [3:0] A, B;
  input [7:0] C;
  output [3:0] out;
  wire clk;
  wire [3:0] A, B;
  wire [7:0] C;
  wire [3:0] out;
  wire [3:0] A_reg;
  wire [3:0] B_reg;
  wire [3:0] out3;
  wire [3:0] out2;
  wire [1:0] out0;
  wire [1:0] out1;
  wire [3:0] out4;
  wire [7:0] C_reg;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, enable, n_0;
  wire n_1, n_2, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_43, n_53, n_68, n_69;
  wire n_74, n_81;
  bitwiseand bitwise0(.A (A_reg), .B (B_reg), .out (out3));
  counter counter0(.clk (clk), .en (enable), .out ({out2[3],
       UNCONNECTED, out2[1:0]}));
  pencoder pencoder0(.A ({A_reg[3:1], UNCONNECTED_HIER_Z}), .Out
       (out0));
  pencoder_5 pencoder1(.A ({B_reg[3:1], UNCONNECTED_HIER_Z0}), .Out
       (out1));
  unequal unequal0(.A (A_reg), .B (B_reg), .out ({out4[3],
       UNCONNECTED2, UNCONNECTED1, UNCONNECTED0}));
  CLKINVX1 g144(.A (out4[3]), .Y (n_43));
  NAND2X6 g1340(.A (n_38), .B (n_37), .Y (enable));
  NAND2BX2 g1341(.AN (n_34), .B (n_36), .Y (n_38));
  OAI21X4 g1342(.A0 (n_68), .A1 (n_35), .B0 (n_32), .Y (n_37));
  OAI21X1 g1343(.A0 (n_28), .A1 (n_33), .B0 (n_29), .Y (n_36));
  CLKAND2X2 g1344(.A (n_30), .B (n_33), .Y (n_35));
  NAND3X1 g1345(.A (C_reg[6]), .B (C_reg[5]), .C (n_74), .Y (n_34));
  NOR3X2 g1346(.A (C_reg[0]), .B (C_reg[1]), .C (C_reg[2]), .Y (n_33));
  NOR2X1 g1347(.A (C_reg[6]), .B (n_74), .Y (n_32));
  NOR2X1 g1349(.A (C_reg[4]), .B (C_reg[5]), .Y (n_31));
  NOR2XL g1350(.A (C_reg[3]), .B (C_reg[5]), .Y (n_30));
  DFFQX1 \C_reg_reg[0] (.CK (clk), .D (C[0]), .Q (C_reg[0]));
  CLKINVX1 g1352(.A (C_reg[5]), .Y (n_53));
  CLKINVX1 g1354(.A (C_reg[4]), .Y (n_29));
  DFFQX1 \C_reg_reg[4] (.CK (clk), .D (C[4]), .Q (C_reg[4]));
  DFFQX2 \C_reg_reg[1] (.CK (clk), .D (C[1]), .Q (C_reg[1]));
  DFFQX4 \C_reg_reg[2] (.CK (clk), .D (C[2]), .Q (C_reg[2]));
  DFFQX4 \C_reg_reg[7] (.CK (clk), .D (C[7]), .Q (C_reg[7]));
  DFFHQX1 \out_reg[0] (.CK (clk), .D (n_25), .Q (out[0]));
  DFFHQX1 \out_reg[1] (.CK (clk), .D (n_26), .Q (out[1]));
  DFFHQX1 \out_reg[2] (.CK (clk), .D (n_24), .Q (out[2]));
  DFFHQX1 \out_reg[3] (.CK (clk), .D (n_23), .Q (out[3]));
  OAI31X1 g1397(.A0 (n_0), .A1 (n_43), .A2 (enable), .B0 (n_19), .Y
       (n_26));
  OAI31X1 g1398(.A0 (n_0), .A1 (n_43), .A2 (enable), .B0 (n_20), .Y
       (n_25));
  OAI31X1 g1399(.A0 (n_0), .A1 (n_43), .A2 (enable), .B0 (n_22), .Y
       (n_24));
  OAI31X1 g1400(.A0 (enable), .A1 (n_43), .A2 (n_0), .B0 (n_21), .Y
       (n_23));
  AOI21X1 g1401(.A0 (out2[3]), .A1 (enable), .B0 (n_18), .Y (n_22));
  AOI21X1 g1402(.A0 (out2[3]), .A1 (enable), .B0 (n_17), .Y (n_21));
  AOI211X2 g1403(.A0 (out2[0]), .A1 (enable), .B0 (n_16), .C0 (n_15),
       .Y (n_20));
  AOI211X2 g1404(.A0 (out2[1]), .A1 (enable), .B0 (n_12), .C0 (n_13),
       .Y (n_19));
  OAI21X1 g1405(.A0 (n_1), .A1 (n_10), .B0 (n_11), .Y (n_18));
  OAI21X1 g1406(.A0 (n_2), .A1 (n_10), .B0 (n_14), .Y (n_17));
  AND2X1 g1407(.A (out3[0]), .B (n_9), .Y (n_16));
  NOR2BX1 g1408(.AN (out1[0]), .B (n_10), .Y (n_15));
  NAND2XL g1409(.A (out3[3]), .B (n_9), .Y (n_14));
  NOR2BX1 g1410(.AN (out1[1]), .B (n_10), .Y (n_13));
  AND2X1 g1411(.A (out3[1]), .B (n_9), .Y (n_12));
  NAND2XL g1412(.A (out3[2]), .B (n_9), .Y (n_11));
  AOI21X2 g1414(.A0 (n_6), .A1 (n_81), .B0 (n_7), .Y (n_10));
  OAI22X2 g1416(.A0 (n_5), .A1 (n_8), .B0 (n_53), .B1 (n_4), .Y (n_9));
  AOI21X1 g1417(.A0 (C_reg[1]), .A1 (C_reg[2]), .B0 (C_reg[3]), .Y
       (n_8));
  AOI21X1 g1418(.A0 (C_reg[6]), .A1 (n_69), .B0 (C_reg[7]), .Y (n_7));
  OAI21XL g1419(.A0 (C_reg[2]), .A1 (C_reg[1]), .B0 (C_reg[3]), .Y
       (n_6));
  NAND3X1 g1420(.A (C_reg[4]), .B (C_reg[6]), .C (C_reg[7]), .Y (n_5));
  DFFQX1 \A_reg_reg[1] (.CK (clk), .D (A[1]), .Q (A_reg[1]));
  DFFQX1 \A_reg_reg[2] (.CK (clk), .D (A[2]), .Q (A_reg[2]));
  DFFQX1 \A_reg_reg[3] (.CK (clk), .D (A[3]), .Q (A_reg[3]));
  DFFQX1 \B_reg_reg[2] (.CK (clk), .D (B[2]), .Q (B_reg[2]));
  DFFQX1 \B_reg_reg[3] (.CK (clk), .D (B[3]), .Q (B_reg[3]));
  DFFQX1 \A_reg_reg[0] (.CK (clk), .D (A[0]), .Q (A_reg[0]));
  DFFQX1 \B_reg_reg[1] (.CK (clk), .D (B[1]), .Q (B_reg[1]));
  DFFQX1 \B_reg_reg[0] (.CK (clk), .D (B[0]), .Q (B_reg[0]));
  NAND2XL g1429(.A (C_reg[6]), .B (C_reg[7]), .Y (n_4));
  CLKINVX1 g1431(.A (out0[1]), .Y (n_2));
  CLKINVX1 g1432(.A (out0[0]), .Y (n_1));
  NAND2BX2 g2(.AN (n_9), .B (n_10), .Y (n_0));
  DFFX1 \C_reg_reg[3] (.CK (clk), .D (C[3]), .Q (C_reg[3]), .QN (n_28));
  CLKINVX1 fopt(.A (n_69), .Y (n_68));
  CLKINVX1 fopt1437(.A (n_31), .Y (n_69));
  CLKINVX3 fopt1439(.A (C_reg[7]), .Y (n_74));
  CLKAND2X2 g1443(.A (n_53), .B (n_74), .Y (n_81));
  DFFQX1 \C_reg_reg[6] (.CK (clk), .D (C[6]), .Q (C_reg[6]));
  DFFQX1 \C_reg_reg[5] (.CK (clk), .D (C[5]), .Q (C_reg[5]));
endmodule

