
// Generated by Cadence Encounter(R) RTL Compiler RC14.25 - v14.20-s046_1

// Verification Directory fv/project_top 

module bitwiseand(A, B, out);
  input [3:0] A, B;
  output [3:0] out;
  wire [3:0] A, B;
  wire [3:0] out;
  AND2X1 g29(.A (B[3]), .B (A[3]), .Y (out[3]));
  AND2X1 g30(.A (B[2]), .B (A[2]), .Y (out[2]));
  AND2XL g31(.A (B[0]), .B (A[0]), .Y (out[0]));
  AND2XL g32(.A (B[1]), .B (A[1]), .Y (out[1]));
endmodule

module counter(clk, en, out);
  input clk, en;
  output [3:0] out;
  wire clk, en;
  wire [3:0] out;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12;
  OR2XL g49(.A (out[3]), .B (n_12), .Y (out[0]));
  OAI2BB1X1 g50(.A0N (count[2]), .A1N (count[3]), .B0 (n_11), .Y
       (out[1]));
  XOR2XL g51(.A (count[3]), .B (count[2]), .Y (n_12));
  CLKINVX1 g52(.A (n_11), .Y (out[3]));
  NOR2XL g53(.A (count[0]), .B (count[1]), .Y (n_11));
  DFFQX1 \count_reg[3] (.CK (clk), .D (n_10), .Q (count[3]));
  NOR2BX1 g63(.AN (en), .B (n_9), .Y (n_10));
  DFFQX1 \count_reg[2] (.CK (clk), .D (n_8), .Q (count[2]));
  AOI21X1 g65(.A0 (count[3]), .A1 (n_4), .B0 (n_7), .Y (n_9));
  NOR2BX1 g66(.AN (en), .B (n_6), .Y (n_8));
  NOR2XL g67(.A (count[3]), .B (n_4), .Y (n_7));
  DFFQX1 \count_reg[1] (.CK (clk), .D (n_3), .Q (count[1]));
  AOI21X1 g69(.A0 (count[2]), .A1 (n_0), .B0 (n_5), .Y (n_6));
  NOR2XL g70(.A (count[2]), .B (n_0), .Y (n_5));
  NAND2BX1 g71(.AN (n_0), .B (count[2]), .Y (n_4));
  AND2XL g72(.A (en), .B (n_2), .Y (n_3));
  DFFQX1 \count_reg[0] (.CK (clk), .D (n_1), .Q (count[0]));
  XOR2XL g74(.A (count[0]), .B (count[1]), .Y (n_2));
  NOR2BX1 g75(.AN (en), .B (count[0]), .Y (n_1));
  NAND2XL g76(.A (count[0]), .B (count[1]), .Y (n_0));
endmodule

module pencoder(A, Out);
  input [3:0] A;
  output [1:0] Out;
  wire [3:0] A;
  wire [1:0] Out;
  wire n_0;
  AO21X1 g17(.A0 (A[1]), .A1 (n_0), .B0 (A[3]), .Y (Out[0]));
  NAND2BX1 g18(.AN (A[3]), .B (n_0), .Y (Out[1]));
  CLKINVX1 g19(.A (A[2]), .Y (n_0));
endmodule

module pencoder_5(A, Out);
  input [3:0] A;
  output [1:0] Out;
  wire [3:0] A;
  wire [1:0] Out;
  wire n_0;
  AO21X1 g17(.A0 (A[1]), .A1 (n_0), .B0 (A[3]), .Y (Out[0]));
  NAND2BX1 g18(.AN (A[3]), .B (n_0), .Y (Out[1]));
  CLKINVX1 g19(.A (A[2]), .Y (n_0));
endmodule

module unequal(A, B, out);
  input [3:0] A, B;
  output [3:0] out;
  wire [3:0] A, B;
  wire [3:0] out;
  wire n_1, n_2, n_3, n_4, n_5, n_6;
  NAND4XL g119(.A (n_3), .B (n_5), .C (n_6), .D (n_4), .Y (out[3]));
  AOI22X1 g120(.A0 (A[1]), .A1 (n_1), .B0 (A[2]), .B1 (n_2), .Y (n_6));
  OA22XL g121(.A0 (A[1]), .A1 (n_1), .B0 (A[2]), .B1 (n_2), .Y (n_5));
  XNOR2XL g122(.A (A[3]), .B (B[3]), .Y (n_4));
  XNOR2XL g123(.A (A[0]), .B (B[0]), .Y (n_3));
  CLKINVX1 g124(.A (B[2]), .Y (n_2));
  CLKINVX1 g125(.A (B[1]), .Y (n_1));
endmodule

module project_top(clk, A, B, C, out);
  input clk;
  input [3:0] A, B;
  input [7:0] C;
  output [3:0] out;
  wire clk;
  wire [3:0] A, B;
  wire [7:0] C;
  wire [3:0] out;
  wire [3:0] A_reg;
  wire [3:0] B_reg;
  wire [3:0] out3;
  wire [3:0] out2;
  wire [1:0] out0;
  wire [1:0] out1;
  wire [3:0] out4;
  wire [7:0] C_reg;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, enable, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_36, n_38;
  bitwiseand bitwise0(.A (A_reg), .B (B_reg), .out (out3));
  counter counter0(.clk (clk), .en (enable), .out ({out2[3],
       UNCONNECTED, out2[1:0]}));
  pencoder pencoder0(.A ({A_reg[3:1], UNCONNECTED_HIER_Z}), .Out
       (out0));
  pencoder_5 pencoder1(.A ({B_reg[3:1], UNCONNECTED_HIER_Z0}), .Out
       (out1));
  unequal unequal0(.A (A_reg), .B (B_reg), .out ({out4[3],
       UNCONNECTED2, UNCONNECTED1, UNCONNECTED0}));
  OAI21X1 g269(.A0 (n_19), .A1 (n_21), .B0 (n_22), .Y (enable));
  NAND4BXL g270(.AN (C_reg[6]), .B (C_reg[7]), .C (n_36), .D (n_20), .Y
       (n_22));
  AOI21X1 g271(.A0 (C_reg[3]), .A1 (n_18), .B0 (C_reg[4]), .Y (n_21));
  OAI21X1 g272(.A0 (C_reg[3]), .A1 (n_18), .B0 (C_reg[4]), .Y (n_20));
  NAND3BX1 g273(.AN (C_reg[7]), .B (C_reg[6]), .C (C_reg[5]), .Y
       (n_19));
  OR3XL g274(.A (C_reg[0]), .B (C_reg[2]), .C (C_reg[1]), .Y (n_18));
  NAND2BX1 g275(.AN (C_reg[4]), .B (n_36), .Y (n_38));
  DFFQXL \C_reg_reg[0] (.CK (clk), .D (C[0]), .Q (C_reg[0]));
  CLKINVX1 g277(.A (C_reg[5]), .Y (n_36));
  DFFQX1 \C_reg_reg[5] (.CK (clk), .D (C[5]), .Q (C_reg[5]));
  DFFQX1 \C_reg_reg[4] (.CK (clk), .D (C[4]), .Q (C_reg[4]));
  DFFQX1 \C_reg_reg[3] (.CK (clk), .D (C[3]), .Q (C_reg[3]));
  DFFQX1 \C_reg_reg[1] (.CK (clk), .D (C[1]), .Q (C_reg[1]));
  DFFQX1 \C_reg_reg[6] (.CK (clk), .D (C[6]), .Q (C_reg[6]));
  DFFQX1 \C_reg_reg[2] (.CK (clk), .D (C[2]), .Q (C_reg[2]));
  DFFQX1 \C_reg_reg[7] (.CK (clk), .D (C[7]), .Q (C_reg[7]));
  DFFQX1 \out_reg[2] (.CK (clk), .D (n_17), .Q (out[2]));
  DFFQX1 \out_reg[3] (.CK (clk), .D (n_16), .Q (out[3]));
  DFFQX1 \out_reg[0] (.CK (clk), .D (n_14), .Q (out[0]));
  DFFQX1 \out_reg[1] (.CK (clk), .D (n_15), .Q (out[1]));
  NAND2XL g490(.A (n_8), .B (n_13), .Y (n_17));
  NAND2XL g491(.A (n_7), .B (n_13), .Y (n_16));
  NAND2XL g492(.A (n_9), .B (n_12), .Y (n_15));
  NAND2XL g493(.A (n_10), .B (n_12), .Y (n_14));
  AOI21X1 g494(.A0 (enable), .A1 (out2[3]), .B0 (n_11), .Y (n_13));
  CLKINVX1 g495(.A (n_11), .Y (n_12));
  NOR4BX1 g496(.AN (out4[3]), .B (n_5), .C (n_6), .D (enable), .Y
       (n_11));
  AOI222XL g497(.A0 (n_6), .A1 (out1[0]), .B0 (n_5), .B1 (out3[0]), .C0
       (out2[0]), .C1 (enable), .Y (n_10));
  AOI222XL g498(.A0 (n_6), .A1 (out1[1]), .B0 (n_5), .B1 (out3[1]), .C0
       (out2[1]), .C1 (enable), .Y (n_9));
  AOI22X1 g499(.A0 (n_6), .A1 (out0[0]), .B0 (n_5), .B1 (out3[2]), .Y
       (n_8));
  AOI22X1 g500(.A0 (n_6), .A1 (out0[1]), .B0 (n_5), .B1 (out3[3]), .Y
       (n_7));
  AOI31X1 g501(.A0 (C_reg[6]), .A1 (n_38), .A2 (n_3), .B0 (C_reg[7]),
       .Y (n_6));
  AOI21X1 g502(.A0 (n_36), .A1 (n_4), .B0 (n_0), .Y (n_5));
  OAI21X1 g503(.A0 (C_reg[3]), .A1 (n_1), .B0 (C_reg[4]), .Y (n_4));
  NAND2XL g504(.A (n_36), .B (n_2), .Y (n_3));
  OAI21X1 g505(.A0 (C_reg[2]), .A1 (C_reg[1]), .B0 (C_reg[3]), .Y
       (n_2));
  DFFQX1 \A_reg_reg[1] (.CK (clk), .D (A[1]), .Q (A_reg[1]));
  DFFQX1 \A_reg_reg[2] (.CK (clk), .D (A[2]), .Q (A_reg[2]));
  DFFQX1 \A_reg_reg[3] (.CK (clk), .D (A[3]), .Q (A_reg[3]));
  DFFQX1 \B_reg_reg[2] (.CK (clk), .D (B[2]), .Q (B_reg[2]));
  DFFQX1 \B_reg_reg[3] (.CK (clk), .D (B[3]), .Q (B_reg[3]));
  DFFQX1 \B_reg_reg[1] (.CK (clk), .D (B[1]), .Q (B_reg[1]));
  DFFQX1 \A_reg_reg[0] (.CK (clk), .D (A[0]), .Q (A_reg[0]));
  DFFQX1 \B_reg_reg[0] (.CK (clk), .D (B[0]), .Q (B_reg[0]));
  AND2X1 g514(.A (C_reg[1]), .B (C_reg[2]), .Y (n_1));
  NAND2XL g515(.A (C_reg[7]), .B (C_reg[6]), .Y (n_0));
endmodule

