
// Generated by Cadence Encounter(R) RTL Compiler RC14.25 - v14.20-s046_1

// Verification Directory fv/project_top 

module bitwiseand(A, B, out);
  input [3:0] A, B;
  output [3:0] out;
  wire [3:0] A, B;
  wire [3:0] out;
  AND2X1 g29(.A (B[3]), .B (A[3]), .Y (out[3]));
  AND2X1 g30(.A (B[2]), .B (A[2]), .Y (out[2]));
  AND2XL g31(.A (B[0]), .B (A[0]), .Y (out[0]));
  AND2XL g32(.A (B[1]), .B (A[1]), .Y (out[1]));
endmodule

module counter(clk, en, out);
  input clk, en;
  output [3:0] out;
  wire clk, en;
  wire [3:0] out;
  wire [3:0] count;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_16, n_31;
  NAND2XL g91(.A (n_12), .B (n_11), .Y (out[0]));
  OAI2BB1X1 g92(.A0N (count[2]), .A1N (count[3]), .B0 (n_12), .Y
       (out[1]));
  CLKINVX1 g94(.A (n_12), .Y (out[3]));
  NOR2XL g95(.A (count[1]), .B (count[0]), .Y (n_12));
  CLKINVX1 g98(.A (count[0]), .Y (n_16));
  XNOR2XL g2(.A (count[3]), .B (count[2]), .Y (n_11));
  DFFQX4 \count_reg[3] (.CK (clk), .D (n_10), .Q (count[3]));
  NOR2XL g151(.A (n_9), .B (n_0), .Y (n_10));
  DFFQX4 \count_reg[2] (.CK (clk), .D (n_8), .Q (count[2]));
  AOI21XL g153(.A0 (count[3]), .A1 (n_4), .B0 (n_7), .Y (n_9));
  NOR2XL g154(.A (n_5), .B (n_0), .Y (n_8));
  NOR2XL g155(.A (count[3]), .B (n_4), .Y (n_7));
  DFFQX4 \count_reg[1] (.CK (clk), .D (n_6), .Q (count[1]));
  NOR2XL g157(.A (n_3), .B (n_0), .Y (n_6));
  XNOR2XL g158(.A (count[2]), .B (n_31), .Y (n_5));
  DFFHQX1 \count_reg[0] (.CK (clk), .D (n_2), .Q (count[0]));
  NAND2XL g160(.A (count[2]), .B (n_31), .Y (n_4));
  XNOR2XL g161(.A (count[0]), .B (count[1]), .Y (n_3));
  NOR2BX1 g162(.AN (n_16), .B (n_0), .Y (n_2));
  CLKINVX1 g164(.A (en), .Y (n_0));
  NOR2BX1 g165(.AN (count[1]), .B (n_16), .Y (n_31));
endmodule

module pencoder(A, Out);
  input [3:0] A;
  output [1:0] Out;
  wire [3:0] A;
  wire [1:0] Out;
  wire n_0, n_1;
  OAI21X1 g17(.A0 (A[2]), .A1 (n_0), .B0 (n_1), .Y (Out[0]));
  NAND2BX1 g18(.AN (A[2]), .B (n_1), .Y (Out[1]));
  CLKINVX1 g19(.A (A[3]), .Y (n_1));
  CLKINVX1 g20(.A (A[1]), .Y (n_0));
endmodule

module pencoder_5(A, Out);
  input [3:0] A;
  output [1:0] Out;
  wire [3:0] A;
  wire [1:0] Out;
  wire n_0, n_1;
  OAI21X1 g17(.A0 (A[2]), .A1 (n_0), .B0 (n_1), .Y (Out[0]));
  NAND2BX1 g18(.AN (A[2]), .B (n_1), .Y (Out[1]));
  CLKINVX1 g19(.A (A[3]), .Y (n_1));
  CLKINVX1 g20(.A (A[1]), .Y (n_0));
endmodule

module unequal(A, B, out);
  input [3:0] A, B;
  output [3:0] out;
  wire [3:0] A, B;
  wire [3:0] out;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  NAND4XL g113(.A (n_7), .B (n_8), .C (n_0), .D (n_1), .Y (out[3]));
  AOI22X1 g114(.A0 (A[0]), .A1 (n_3), .B0 (A[2]), .B1 (n_5), .Y (n_8));
  AOI22X1 g115(.A0 (B[0]), .A1 (n_4), .B0 (B[2]), .B1 (n_6), .Y (n_7));
  INVXL g119(.A (A[2]), .Y (n_6));
  INVXL g120(.A (B[2]), .Y (n_5));
  INVXL g121(.A (A[0]), .Y (n_4));
  INVXL g123(.A (B[0]), .Y (n_3));
  XNOR2XL g2(.A (A[3]), .B (B[3]), .Y (n_1));
  XNOR2XL g124(.A (A[1]), .B (B[1]), .Y (n_0));
endmodule

module project_top(clk, A, B, C, out);
  input clk;
  input [3:0] A, B;
  input [7:0] C;
  output [3:0] out;
  wire clk;
  wire [3:0] A, B;
  wire [7:0] C;
  wire [3:0] out;
  wire [3:0] A_reg;
  wire [3:0] B_reg;
  wire [3:0] out3;
  wire [3:0] out2;
  wire [1:0] out0;
  wire [1:0] out1;
  wire [3:0] out4;
  wire [7:0] C_reg;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, enable, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_64, n_66, n_94, n_96, n_98, n_99, n_100, n_101;
  bitwiseand bitwise0(.A (A_reg), .B (B_reg), .out (out3));
  counter counter0(.clk (clk), .en (enable), .out ({out2[3],
       UNCONNECTED, out2[1:0]}));
  pencoder pencoder0(.A ({A_reg[3:1], UNCONNECTED_HIER_Z}), .Out
       (out0));
  pencoder_5 pencoder1(.A ({B_reg[3:1], UNCONNECTED_HIER_Z0}), .Out
       (out1));
  unequal unequal0(.A (A_reg), .B (B_reg), .out ({out4[3],
       UNCONNECTED2, UNCONNECTED1, UNCONNECTED0}));
  NAND2X4 g1354(.A (n_47), .B (n_48), .Y (enable));
  AOI31X4 g1355(.A0 (C_reg[3]), .A1 (n_43), .A2 (n_42), .B0 (n_45), .Y
       (n_48));
  CLKAND2X3 g1356(.A (n_46), .B (n_44), .Y (n_47));
  NAND3X1 g1357(.A (n_36), .B (C_reg[5]), .C (C_reg[4]), .Y (n_46));
  NOR3X4 g1358(.A (n_42), .B (n_40), .C (n_33), .Y (n_45));
  NAND2X1 g1359(.A (n_39), .B (n_38), .Y (n_44));
  NOR2X2 g1360(.A (n_64), .B (n_37), .Y (n_43));
  NAND2BX4 g1361(.AN (n_49), .B (n_41), .Y (n_42));
  NOR2X4 g1362(.A (C_reg[0]), .B (C_reg[1]), .Y (n_41));
  CLKINVX3 g1363(.A (n_39), .Y (n_40));
  NOR2X2 g1364(.A (C_reg[6]), .B (n_35), .Y (n_39));
  CLKINVX1 g1366(.A (n_38), .Y (n_66));
  NOR2X1 g1367(.A (C_reg[5]), .B (C_reg[4]), .Y (n_38));
  CLKINVX2 g1368(.A (n_36), .Y (n_37));
  NOR2X2 g1369(.A (n_50), .B (n_96), .Y (n_36));
  CLKINVX3 g1370(.A (n_35), .Y (C_reg[7]));
  CLKINVX4 g1371(.A (n_50), .Y (n_35));
  DFFQX4 \C_reg_reg[7] (.CK (clk), .D (C[7]), .Q (n_50));
  DFFQX1 \C_reg_reg[4] (.CK (clk), .D (C[4]), .Q (C_reg[4]));
  DFFQX4 \C_reg_reg[3] (.CK (clk), .D (C[3]), .Q (C_reg[3]));
  DFFQX4 \C_reg_reg[6] (.CK (clk), .D (C[6]), .Q (C_reg[6]));
  BUFX3 g1378(.A (n_49), .Y (C_reg[2]));
  DFFQX2 \C_reg_reg[2] (.CK (clk), .D (C[2]), .Q (n_49));
  DFFQX4 \C_reg_reg[1] (.CK (clk), .D (C[1]), .Q (C_reg[1]));
  CLKINVX2 g1384(.A (C_reg[5]), .Y (n_64));
  DFFQX4 \C_reg_reg[5] (.CK (clk), .D (C[5]), .Q (C_reg[5]));
  NAND2BX2 g2(.AN (C_reg[3]), .B (n_64), .Y (n_33));
  DFFHQX1 \out_reg[2] (.CK (clk), .D (n_30), .Q (out[2]));
  DFFQX4 \out_reg[3] (.CK (clk), .D (n_29), .Q (out[3]));
  DFFQX4 \out_reg[0] (.CK (clk), .D (n_31), .Q (out[0]));
  DFFQX4 \out_reg[1] (.CK (clk), .D (n_32), .Q (out[1]));
  OAI31X1 g1325(.A0 (n_98), .A1 (n_19), .A2 (n_3), .B0 (n_27), .Y
       (n_32));
  OAI31X1 g1326(.A0 (n_98), .A1 (n_19), .A2 (n_3), .B0 (n_28), .Y
       (n_31));
  OAI21X1 g1327(.A0 (n_19), .A1 (n_20), .B0 (n_26), .Y (n_30));
  OAI21X1 g1328(.A0 (n_19), .A1 (n_20), .B0 (n_25), .Y (n_29));
  AOI211X1 g1329(.A0 (out2[0]), .A1 (enable), .B0 (n_24), .C0 (n_23),
       .Y (n_28));
  AOI211X1 g1330(.A0 (out2[1]), .A1 (enable), .B0 (n_22), .C0 (n_21),
       .Y (n_27));
  AOI222X1 g1331(.A0 (out0[0]), .A1 (n_101), .B0 (out3[2]), .B1 (n_17),
       .C0 (enable), .C1 (out2[3]), .Y (n_26));
  AOI222X2 g1332(.A0 (out0[1]), .A1 (n_100), .B0 (out3[3]), .B1 (n_17),
       .C0 (out2[3]), .C1 (enable), .Y (n_25));
  NOR2BX1 g1333(.AN (out1[0]), .B (n_18), .Y (n_24));
  NOR2BXL g1334(.AN (out3[0]), .B (n_16), .Y (n_23));
  NOR2BX1 g1335(.AN (out1[1]), .B (n_18), .Y (n_22));
  NOR2BXL g1336(.AN (out3[1]), .B (n_16), .Y (n_21));
  NAND2X2 g1337(.A (n_99), .B (n_1), .Y (n_20));
  NAND2X1 g1338(.A (n_16), .B (out4[3]), .Y (n_19));
  NOR2X4 g1340(.A (n_10), .B (n_15), .Y (n_18));
  CLKINVX2 g1341(.A (n_16), .Y (n_17));
  NOR2X4 g1342(.A (n_13), .B (n_14), .Y (n_16));
  NOR2X2 g1343(.A (n_7), .B (n_9), .Y (n_15));
  NOR2X2 g1344(.A (n_12), .B (n_11), .Y (n_14));
  NOR2X2 g1345(.A (n_8), .B (n_64), .Y (n_13));
  NAND3X2 g1346(.A (C_reg[4]), .B (n_94), .C (C_reg[7]), .Y (n_12));
  AOI21X2 g1347(.A0 (C_reg[1]), .A1 (C_reg[2]), .B0 (C_reg[3]), .Y
       (n_11));
  AOI21X2 g1348(.A0 (n_94), .A1 (n_66), .B0 (C_reg[7]), .Y (n_10));
  NOR2X2 g1349(.A (n_4), .B (n_6), .Y (n_9));
  DFFQX1 \A_reg_reg[1] (.CK (clk), .D (A[1]), .Q (A_reg[1]));
  DFFQX4 \A_reg_reg[2] (.CK (clk), .D (A[2]), .Q (A_reg[2]));
  DFFQX1 \A_reg_reg[3] (.CK (clk), .D (A[3]), .Q (A_reg[3]));
  DFFQX4 \B_reg_reg[2] (.CK (clk), .D (B[2]), .Q (B_reg[2]));
  DFFQX1 \B_reg_reg[3] (.CK (clk), .D (B[3]), .Q (B_reg[3]));
  DFFQX1 \B_reg_reg[1] (.CK (clk), .D (B[1]), .Q (B_reg[1]));
  DFFQX1 \A_reg_reg[0] (.CK (clk), .D (A[0]), .Q (A_reg[0]));
  DFFQX1 \B_reg_reg[0] (.CK (clk), .D (B[0]), .Q (B_reg[0]));
  NAND2X1 g1387(.A (C_reg[7]), .B (n_94), .Y (n_8));
  NAND2X2 g1388(.A (n_5), .B (n_64), .Y (n_7));
  NOR2X2 g1389(.A (C_reg[1]), .B (C_reg[2]), .Y (n_6));
  CLKINVX2 g1390(.A (C_reg[7]), .Y (n_5));
  CLKINVX1 g1391(.A (C_reg[3]), .Y (n_4));
  CLKINVX1 fopt(.A (n_2), .Y (n_3));
  CLKINVX1 fopt1365(.A (enable), .Y (n_2));
  CLKINVX1 fopt1366(.A (enable), .Y (n_1));
  CLKINVX2 fopt1401(.A (n_96), .Y (n_94));
  CLKINVX3 fopt1402(.A (C_reg[6]), .Y (n_96));
  CLKINVX1 fopt1403(.A (n_99), .Y (n_98));
  CLKINVX2 fopt1404(.A (n_100), .Y (n_99));
  CLKINVX2 fopt1405(.A (n_18), .Y (n_100));
  CLKINVX1 fopt1406(.A (n_18), .Y (n_101));
  DFFQX4 \C_reg_reg[0] (.CK (clk), .D (C[0]), .Q (C_reg[0]));
endmodule

